package org.arghyam.jalsoochak.tenant.dto.internal;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for individual option/choice in a screen.
 * Used for screens like LANGUAGE_SELECTION, CHANNEL_SELECTION, ITEM_SELECTION.
 * 
 * Key format: OPTION_1, OPTION_2, etc. (auto-generated by system)
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public final class OptionDTO {
    @NotNull(message = "Display order is required")
    @Positive(message = "Display order must be positive")
    private Integer order;
    
    @NotNull(message = "Label is required")
    @Valid
    private LocalizedTextDTO label;
}
