package org.arghyam.jalsoochak.tenant.dto.internal;

import jakarta.validation.Valid;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * DTO for a single screen configuration in the Glific conversation flow.
 * 
 * A screen represents a single interaction point in the WhatsApp conversation.
 * Examples: LANGUAGE_SELECTION, CHANNEL_SELECTION, INTRO_MESSAGE, ISSUE_REPORT, etc.
 * 
 * Fields are optional to support different screen types:
 * - Simple message screens: only 'message' field
 * - Selection screens: 'prompt', 'options', 'confirmationTemplate'
 * - Issue report screens: 'prompt', 'confirmationTemplate', 'reasons'
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public final class ScreenConfigDTO {
    /**
     * Prompt text for selection screens (e.g., "Please select your preferred language").
     * Not used for simple message screens.
     */
    @Valid
    private LocalizedTextDTO prompt;
    
    /**
     * Options for selection screens.
     * Key format: OPTION_1, OPTION_2, etc. (auto-generated by system)
     * Example: { "OPTION_1": { "order": 1, "label": {...} }, ... }
     */
    private Map<String, @Valid OptionDTO> options;
    
    /**
     * Reasons for issue report screens.
     * Key format: REASON_1, REASON_2, etc. (auto-generated by system)
     * Example: { "REASON_1": { "order": 1, "label": {...} }, ... }
     */
    private Map<String, @Valid OptionDTO> reasons;
    
    /**
     * Confirmation message template for selection/action screens.
     * Supports placeholders like {language}, {channel}, {item}, etc.
     * Example: "Your preferred language has been set to {language}."
     */
    @Valid
    private LocalizedTextDTO confirmationTemplate;
    
    /**
     * Simple message for message-only screens (e.g., INTRO_MESSAGE, CLOSING_MESSAGE).
     * Supports placeholders like {name}, etc.
     * Example: "Hello {name}, please send a clear meter reading image."
     */
    @Valid
    private LocalizedTextDTO message;
}
