-- ============================================================
-- DIM USER SCHEME MAPPING TABLE
-- ============================================================

CREATE TABLE analytics_schema.dim_user_scheme_mapping_table (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID         NOT NULL UNIQUE,
    user_id     INT          NOT NULL REFERENCES analytics_schema.dim_user_table(user_id),
    scheme_id   INT          NOT NULL REFERENCES analytics_schema.dim_scheme_table(scheme_id),
    ai_reading  NUMERIC,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    status      INT          NOT NULL
);
